[browser]
# Reduce potential race conditions
gatherUsageStats = false

[client]
# Improve connection handling
caching = true
displayEnabled = true

[global]
email = ""

[server]
enableCORS = false
enableXsrfProtection = false
maxMessageSize = 50
# Improve concurrent user handling
maxUploadSize = 50
runOnSave = false

[theme]
backgroundColor = "#F8FAFB"
font = "sans serif"
primaryColor = "#0A9396"
secondaryBackgroundColor = "#E8F4F8"
textColor = "#1C2B3A"
